const DUMMY_DATA = [
  {
    id: "order1",
    orderNumber: "52364",
    name: "Ралица Видева",
    orderAmount: "200 лв.",
    invoice: "yes",
    isPaid: "no",
    newClient: "yes",
  },
  {
    id: "order2",
    orderNumber: "12589",
    name: "Иван Стоянов",
    orderAmount: "20 лв.",
    invoice: "yes",
    isPaid: "yes",
    newClient: "yes",
  },
  {
    id: "order3",
    orderNumber: "65442",
    name: "Виктор Иванов",
    orderAmount: "25 лв.",
    invoice: "yes",
    isPaid: "yes",
    newClient: "no",
  },
  {
    id: "order4",
    orderNumber: "85468",
    name: "Пламен Тодоров",
    orderAmount: "156 лв.",
    invoice: "yes",
    isPaid: "yes",
    newClient: "no",
  },
  {
    id: "order5",
    orderNumber: "68523",
    name: "Катя Тошева",
    orderAmount: "39 лв.",
    invoice: "yes",
    isPaid: "yes",
    newClient: "no",
  },
  {
    id: "order6",
    orderNumber: "71235",
    name: "Симеон Колев",
    orderAmount: "106 лв.",
    invoice: "yes",
    isPaid: "yes",
    newClient: "no"
  },
  {
    id: "order7",
    orderNumber: "91235",
    name: "Анастасия Бонева",
    orderAmount: "154 лв.",
    invoice: "yes",
    isPaid: "yes",
    newClient: "no"
  },
  {
    id: "order8",
    orderNumber: "65454",
    name: "Яна Пеева",
    orderAmount: "63 лв.",
    invoice: "yes",
    isPaid: "yes",
    newClient: "no"
  },
  {
    id: "order9",
    orderNumber: "54155",
    name: "Янислав Шопов",
    orderAmount: "59 лв.",
    invoice: "yes",
    isPaid: "yes",
    newClient: "no"
  },
  {
    id: "order10",
    orderNumber: "65134",
    name: "Благой Симеонов",
    orderAmount: "38 лв.",
    invoice: "yes",
    isPaid: "yes",
    newClient: "no"
  },
  {
    id: "order11",
    orderNumber: "85632",
    name: "Тодор Киров",
    orderAmount: "67 лв.",
    invoice: "yes",
    isPaid: "yes",
    newClient: "no"
  },
  {
    id: "prada",
    orderNumber: "52364",
    name: "Ralitsa Videva",
    orderAmount: "200 лв.",
  },
  {
    id: "prada",
    orderNumber: "52364",
    name: "Ralitsa Videva",
    orderAmount: "200 лв.",
  },
  {
    id: "prada",
    orderNumber: "52364",
    name: "Ralitsa Videva",
    orderAmount: "200 лв.",
  },
];
export default DUMMY_DATA;
